pipeline{
    agent{
        docker{
            image 'ujnvdprasad/slave-image:v1'
            args '--user root -v /var/lib/docker.sock:/var/lib/docker.sock'
        }
    }
    stages {
      stage('Checkout') {
        steps {
          sh 'echo passed'
          git 'https://github.com/ujnvdprasad/Jenkins-Docker-SonarQube.git'
        }
      }
      stage('Build and Test') {
        steps {
          sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd spring-boot-app && mvn clean package'
        }
      }
    }
}
